### ISSUE TITLE
Installed Package on Umbraco V13. Error upon generating content

### ISSUE THREAD

**Issue by TomChancer** [Smayke95/Umbraco.OpenAI#1]
Hey!

Installed your package on an Umbraco 13.2.2 site, we are experiencing an issue however in which the generate method fails with a System CorLib error as seen here:

![image](https://github.com/Smayke95/Umbraco.OpenAI/assets/56866089/8b8932c2-790c-486c-b246-bee1d5a8949e)

Wondering if the project has been built to handle V13 sites on .net Core 8?

**Comment by Smayke95** [comment]
@TomChancer do you use **Behavior model: Adventurous**? 
In meantime, OpenAI made some updates which disabled using temperature this high. Try use lower behavior model.

![image](https://github.com/Smayke95/Umbraco.OpenAI/assets/11999303/08cfa069-9359-4d83-a13e-e08484bd2115)

I will release update which will fix this, so it uses lower temperature for generating content with Adventurous behavior model.

**Comment by Smayke95** [comment]
@TomChancer version 1.0.6 is released. Please check it out.

**Comment by remkovb** [comment]
Hi, still getting the same exception, installed version 1.0.6. No matter what behaviour model I use, or any parameter always getting this exception and error message.

`
{
    "ExceptionMessage": "Failed to generate text from OpenAI API",
    "ExceptionType": "System.InvalidOperationException, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
    "StackTrace": "   at S95.Umbraco.OpenAI.Services.OpenAiService.Generate(GenerateRequest request)\r\n   at S95.Umbraco.OpenAI.Controllers.OpenAiController.Generate(GenerateRequest request)\r\n   at lambda_method30139(Closure, Object)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"
}`

**Comment by Smayke95** [comment]
@remkovb can you write me which Umbraco version you are using? Also it would be great if you can write which data you want to generate, so I can use same to test this.

**Comment by remkovb** [comment]
I'm sorry, it was because I didn't have paid account yet. After paying for budget it worked!
